# Generated by Django 3.2.7 on 2021-10-07 11:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_review_updown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='updown',
        ),
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
